### ISSUE TITLE
Merge this repository with https://github.com/rubygems/bundler.github.io

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/bundler-site#591]
This is not a big deal, really, but it feels a bit cumbersome to use two different repositories.

As far as I understand, we could either:

* Use a branch in this repository to deploy to GitHub Pages, instead of a separate repository.

or

* Stop deploying to GitHub Pages and use Heroku instead.

The former seems simpler, but the latter seems slightly more desirable to me, because we currently have a permanently red Heroku staging pipeline, just to keep Heroku review apps working, which is very useful. I guess we could fix that actually having a staging site that uses heroku, but at that point we may as well switch everything to Heroku.

Anways, this is not a big deal, but it could be an interesting/fun exercise for someone willing to play around with Heroku and Github Pages.

## Summary

- Code changes: https://github.com/rubygems/bundler-site/compare/fe5036b...b16c5ef

### `rubygems/bundler-site`
- [x] Set @tnir as Maintain or higher (= Admin) in `rubygems/bundler-site` (#730)
- [x] Manually push `master` branch in https://github.com/rubygems/bundler.github.io to this repo as `gh-pages` and keep up to date (as possible).
- [x] Enable GitHub Pages with publishing source of `gh-pages` branch and `/` (root)
- [-] Set @tnir as Admin in `rubygems/bundler-site` (#730)
- [x] Set a custom domain of `bundler.io` in GitHub Pages at https://github.com/rubygems/bundler-site/settings/pages
- [x] Create a PR to change the deploy target from `rubygems/bundler.github.io` to `rubygems/bundler-site` in [ci/deploy.rake](https://github.com/rubygems/bundler-site/blob/bbb543be924b8a812aba486bf7cde1f5e03e8c2e/lib/tasks/ci/deploy.rake#L21-L41) (#789)
- [x] Review and merge the PR above #789

### `rubygems/bundler.github.io`
- [x] Set @tnir as Admin in `rubygems/bundler.github.io` (#730)
- [x] Unset a custom domain in the old repo.
- [x] Remove CNAME in rubygems/bundler.github.io: https://github.com/rubygems/bundler.github.io/commit/cf6cdd77cc51c9104feecb947cc9af27ce0f6248
- [x] Disable GitHub Pages by selecting `None` as the publishing source at https://github.com/rubygems/bundler.github.io/settings/pages
- [x] (optional) Add a commit with the deprecation notice on the default branch to README.
- [x] (optional) Archive the repo

**Comment by hsbt** [comment]
+1

**Comment by tnir** [comment]
@deivid-rodriguez Any update?

+1 for the former as deploying to Heroku looks much slower than the current `middleman build` (50-60s) as you can see in the review apps (3-4 min in multiple PRs, I guess). The former also provides "deploy logs" to all contributors. The former looks like an easy way enough to me and I finished to make a proof of concept of it.

**Comment by deivid-rodriguez** [comment]
No updates @tnir, I never planned to tackle this one myself actually.

So feel free to move this forward. So your plan is to deploy to GitHub Pages within this repo and also keep review apps? I think that would be ideal.

**Comment by tnir** [comment]
@deivid-rodriguez Yes, my plan is:

- to enable GitHub Pages in this repo.
- to push master branch in https://github.com/rubygems/bundler.github.io to this repo as gh-pages.
- to set custom domain of GitHub Pages to `bundler.io` in this repo.
- to unset custom domain in the old repo.
- to add deprecation notice on the default branch to README in the old repo.
- to archive the old repo.

and

- not to change anyhing on review apps in this repo.

The former tasks can be done with Admin role in these two repositories.

**Comment by deivid-rodriguez** [comment]
Ok, so from now on deployment will be just `bundle exec middleman build`, and configure GitHub Pages to deploy the `build` folder in the master branch, correct?

**Comment by tnir** [comment]
While we can do so, I am not a fan of it. Use of the default branch "`master`" would not be changed, so it would be a source branch. On the other hand, `gh-pages` branch is to be an artifact branch and does exist only as a source of the static site hosting. These are my plan. What do you think?

**Comment by deivid-rodriguez** [comment]
Ah, ok, yeah using the `gh-pages` branch sounds good too, I just misunderstood your second bullet point above.

I think we can start with a PR to migrate the deploy task? I think we only need to change it to push to the `gh-pages` branch inside this repository, instead of pushing to an external repository (and removing all complexities of doing that), correct?

**Comment by tnir** [comment]
Yes, you are right!

**Comment by tnir** [comment]
1. Set a custom domain as `bundler.io` in GitHub Pages at https://github.com/rubygems/bundler-site/settings/pages (currently set as `http://blog.rubygems.org/bundler-site/`)

The above is the instruction a person with Admin role can do whenever they wants to do from now (since the publishing sources are identical in `bunder-site` and `bundler.github.io` repos). @hsbt Can you try it?

### Resources
- https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by tnir** [comment]
Prior to the above, as an Org admin, you should make sure if `bundler.io` exists at `https://github.com/organizations/rubygems/settings/pages and add it if not.

**Comment by hsbt** [comment]
Now, I removed custom domain setting from `bundler.github.io` and added custom domain as `bundler.io` to `bundler-site`.

**Comment by tnir** [comment]
Thanks for unsetting the custom domain in the old repo.

Just removing `CNAME` from `rubygems/bundler.github.io` repo caused occupying `https://blog.rubygems.org/bundler.github.io/` on `blog.rubygems.org`. @hsbt Could you un-archive it to set `None` as the publishing source at https://github.com/rubygems/bundler.github.io/settings/pages?

**Comment by tnir** [comment]
> (optional) Add a commit with the deprecation notice on the default branch to README.

Also I prefer adding a link to this repo to README.md in https://github.com/rubygems/bundler.github.io.

**Comment by hsbt** [comment]
>rubygems/bundler.github.io

I disabled to publish github pages from `rubygems/bundler.github.io` and archive it.

**Comment by tnir** [comment]
Thank you. All tasks were done, so closing.

**Comment by deivid-rodriguez** [comment]
Thanks both, I wanted to do this for a long time 🎉

**Comment by simi** [comment]
:partying_face:

**Comment by tnir** [comment]
Thank you all.

The problem we were having was just filed at: https://github.com/orgs/community/discussions/27583
